<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SteadyDesk.ScheduleChecks</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteadyDesk\SteadyDesk.csproj" />
  </ItemGroup>
</Project>
